### ISSUE TITLE
File size

### ISSUE THREAD

**Issue by zenorocha** [liferay/senna.js#158]
At this moment Senna is 17kb gzipped which is very big for a JS library.

Is there a way for us to optimize it? /cc @mairatma 

<img width="186" alt="screen shot 2016-07-01 at 12 15 33 pm" src="https://cloud.githubusercontent.com/assets/398893/16532260/c024bd4c-3f85-11e6-8041-5df52f013c27.png">

**Comment by yuchi** [comment]
Did you try to build it with [Rollup.js](http://rollupjs.org/)? It should reduce the file size by using tree shaking.

**Comment by eduardolundgren** [comment]
@mairatma Would that be possible?

**Comment by mairatma** [comment]
Yep, we should be able to use it, the only difference is that the final senna.js file would not include all of Metal.js, since Rollup.js will remove any code from Metal.js not being used directly by senna (that's why it will be smaller in the end).

That shouldn't be important since this file is supposed to be a way to use senna standalone, right? In projects that use both senna and metal the ideal would be to build them together, otherwise using the rollup build would cause duplicate Metal.js code to be added to the page.

**Comment by yuchi** [comment]
> Yep, we should be able to use it, the only difference is that the final senna.js file would not include all of Metal.js, since Rollup.js will remove any code from Metal.js not being used directly by senna (that's why it will be smaller in the end).

Exactly why I proposed it in the first place.

> […] otherwise using the rollup build would cause duplicate Metal.js code to be added to the page.

And that’s what should be happening right now.

**Comment by mairatma** [comment]
You're right, that would already happen now if the global senna build is used. The thing is that now you can just include senna and have both Metal.js and Senna.js available on globals, but with the Rollup build this won't be doable anymore. But, like I said, that shouldn't be important, people using senna's build want Senna.js, not Metal.js.

**Comment by yuchi** [comment]
> […] you can just include senna and have both Metal.js and Senna.js available on globals […]

Oh right! But if you think about it it’s not a good thing!

Anyway if you move to Rollup it’s probably a good idea to move to named exports instead of classes. This way tree shaking build engines (be it Rollup or webpack’s) can correctly shim it down to the minimal dependency tree.

```js
export default class DOM {
  // canNOT be extracted
  static querySelector(s, n) { return (n||document).querySelector(s); }
}
```

```js
// CAN be extracted
export function querySelector(s, n) { return (n||document).querySelector(s); }
// or
export const querySelector = (s, n) => (n||document).querySelector(s);
```

**Comment by b0jan** [comment]
Shoudn't be ~8KB?

**Comment by mairatma** [comment]
@b0jan yes, but the way it's currently being built is including a bunch of dead code due to external dependencies.

I have a plan to try to fix this using rollup, by making metal use more named exports like @yuchi has recommended. At first we thought that wouldn't be possible, as changing the export calls  would break existing imports, but I've actually realized that we can do both named and default imports for backwards compatibility, and so we can take advantage of rollup here. So let me grab this issue.

**Comment by b0jan** [comment]
@mairatma Oh ok, home page was saying it was around 8kb. Can you tell me when this can be fixed?

**Comment by mairatma** [comment]
I don't have an exact timeline, but I'm trying to get it done this week. As soon as it is I'll let you know here, ok?

**Comment by jbalsas** [comment]
Hey, we actually merged in the rollup build a while ago and we haven't really noticed a significant decrease in size. We are currently at the numbers this post started (we gained a bit of weight for a while).

I tested with Webpack3 as well, and the numbers didn't differ a lot, so we'll need to take a closer look at where the extra bits are coming from...
