### ISSUE TITLE
Delay/throttle cashed flip

### ISSUE THREAD

**Issue by iskrisis** [liferay/senna.js#170]
When going to cashed url, the flip is almost instatinous. This is awesome but for percived performance it would be good to have some fast delay so transitions have time to finish.

How too set minimum time before senna flips the screens?

Thank you!

**Comment by mjbradford89** [comment]
Hey @krisak,

There is no way to do this out of the box.  One way to get this to work though is to extend the App class and override the `doNavigate_` and `finalizeNavigate_` method.  It may look something like:

```javascript
import App from 'senna/src/app/App';

class LiferayApp extends App {
     doNavigate_(path, opt_replaceHistory) {
          this.minTimeReached = false;
          this.addLoadingMask();
          setTimeout(() => {
               if (!this.isNavigationPending) {
                    this.removeLoadingMask();
               }
               this.minTimeReached = true;
          }, 2000);

          return super.doNavigate(path, opt_replaceHistory);
     }

     finalizeNavigate_(path, nextScreen) {
          if (this.minTimeReached) {
               this.removeLoadingMask();
          }
          super.finalizeNavigate_(path, nextScreen);
     }
}
```

I haven't tested this, it's just an idea for one way it could work.

I'm going to label this issue a feature request, so there is a possibility we add this functionality in the future.

**Comment by krisak** [comment]
Not realy sure how to build this since the senna.js has to import all kinds of other things (HtmlScreen, RequestScreen, Route, Screen). But i havent tried enough probably.

After thinking aboit it a lot. I think it would be very useful for this funcionality. It will be probably useful for almost every project. Percieved performance is not only about speed but also about consistency. When you make the instant loads (cashed ones) 400ms transition then its much more easier to wait 1s for proper request. 

I think it would be realy useful to have this functionality. Iam just not sure how to implement it properly.

**Comment by fernandosouza** [comment]
Hey, @krisak. Could you explain how you are implementing those transitions?

**Comment by krisak** [comment]
I am not actualy. I would have to dig into senna to add the throttle i think is needed.

I am using senna not for traditional SPAs but as sugar for normal presentation websites like this for example (https://designreader.org/). 

Idealy there would be same time to transition everywhere (lets say 600ms) this is of course not possible but its OK when you make normal request. 
```
click link - start transition out (200ms) + start request -  request finished after 400ms - flip / replace content - tranistion in (200ms)
```
The problem is when requesting already visited cashed page. Senna is awesome fast but it goes like this
```
click link - start transition out (200ms) - content fliped after 20ms while transitioning out - transition in cuts the transition out in middle (css trans work like that).
```
Now you might say that instant trans is better than 600ms trans and you are probably right - the rpoblem is that it cannot be consistent. In our experience its much better to have smoother flow of little longer transitions than switching between instant and waiting. Lot of users get suprised once they click on cashed page - what just happened? Why its suddenly so fast.

This could be possible to solve if there was way to set timeout before fliping content. Flip only if  minimum time has passed.

**Comment by fernandosouza** [comment]
In a nutshell, what you want is a way to delay the request and also delay the page content change even for cached pages. Right?

**Comment by brunobasto** [comment]
@fernandosouza, I don't think he wants to delay the request. Just the transition from one screen to the next one.

**Comment by krisak** [comment]
I dont know what you mean by delaing the request but yes delay the content change. Delay content change if the content change would too fast - faster than specified delay (it happens with cashed pages but can also happen if you want longer transitions and make very fast request).

Basicaly if somebody makes use of .senna-loading class like here https://github.com/liferay/senna.js/blob/master/build/senna.css 

The out transition will not work for cashed pages. You will want to have the times of css tranistions corespond to senna timing of flips.

**Comment by krisak** [comment]
I dont have time to show what happens with the flip on this site where i use senna i try to go around it but there is this inconsistency like this still.

http://imgur.com/2fpQ0Wj

**Comment by sintro** [comment]
So, there are 3 hooks, where something like promise pausing mechanism should be implemented already (i thought so): 'beforeNavigate','startNavigate', 'endNavigate'. Today I spent maybe about 1.5 hours to get that I can not pause page flipping. For example, to perform fade animation on pages. This wondered me.
Still no progress on this feature?

**Comment by brunobasto** [comment]
hey @krisak, would something like that work?

```
Object.keys(app.surfaces).forEach(s => {
  app.surfaces[s].setTransitionFn(
    (from, to) => new Promise((resolve, reject) => {
      setTimeout(() => {
        // senna.Surface.defaultTransition.apply(this, []);
        // custom logic using elements from and to
        console.log('resolving');
        resolve();
      }, 1000);
  }))
});
```

Basically the idea is go over your surfaces and change the default [transitionFn](https://github.com/liferay/senna.js/blob/master/src/surface/Surface.js#L194) to whatever you want.

We should probably add an easier way to do this from within the app constructor / data attributes.

**Comment by brunobasto** [comment]
@sintro, what do you mean by `promise pausing`? If you set a custom transition function to your surfaces, like in the example above, would that help?

**Comment by sintro** [comment]
@brunobasto I mean the possibility for coder to delay the execution of beforeNavigate -> startNavigate -> endNavigate  by using some mechanisms like promises, for example. Can not tell exactly how the can be implemented, but I think this will be something similar to your sample here https://github.com/liferay/senna.js/issues/170#issuecomment-286629854

**Comment by brunobasto** [comment]
@sintro, I see. Yeah, if you wan't to do transitions, I think the example posted is probably enough. If you want to pause beforeNavigate, startNavigate, etc for other reasons, then we can discuss what the use cases are.

**Comment by sintro** [comment]
@brunobasto 
Sure, I will think about it, may be will face this task in future, but for now I solved my problem, thanks to your advice. 
The only problem is that it was not very beautiful code, as I had to just add timeout in transitions and perform all the effects in beforeNavigate and endNavigate hooks.

**Comment by wincent** [comment]
We're about to archive this repo and mark it as read-only. As [explained here](https://github.com/liferay/liferay-frontend-projects/blob/eb83cc6c28fc68e6e70aed8a22f1b2fdf31ac277/maintenance/projects/senna/README.md) the Senna code base has been ingested into Liferay DXP itself in the form of the `frontend-js-spa-web` module, and we have migrated the v2.x history over into [the liferay-frontend-projects monorepo](https://github.com/liferay/liferay-frontend-projects) so that we can keep our stuff together (and have uniform testing, linting, building etc) and will cut any necessary maintenance releases from there.

So as to clean out stale issues, I am closing anything that hasn't had any activity in the last year. If this is still relevant, would you mind [opening an issue over there](https://github.com/liferay/liferay-frontend-projects/issues/new?assignees=&labels=senna&template=senna.md) instead?
