### ISSUE TITLE
It's adding 2 assets when using wiredep 

### ISSUE THREAD

**Issue by pragmaticivan** [liferay/senna.js#174]
It's declared on bower.json as:

```
  "main": [
    "build/globals/senna-min.js",
    "build/globals/senna.js",
    "build/senna.css"
  ],
```

When installing `bower install senna --save` It's adding both `senna.js` and `senna-min.js` into the html file.

Is that normal?

**Comment by mairatma** [comment]
You're right, we should only be passing either one or the other to `main`, since there are many tools like `wiredep` that automatically add these files. I just checked the [bower config specification](https://github.com/bower/spec/blob/master/json.md) and it says that `main` shouldn't have minified files, so I'll remove that one then.
