### ISSUE TITLE
Review saucelabs connection

### ISSUE THREAD

**Issue by pragmaticivan** [liferay/senna.js#178]
All the CI tests are failing due to bad setup with saucelabs, maybe the key has changed or something like that.

**Comment by mairatma** [comment]
Yes, they only fail for pull requests though, if you check the usual tests they all pass. This is a problem with the configuration, because saucelabs doesn't allow usage of encrypted environement variables for the saucelabs access keys in the way we're using them. I fixed this for the metal.js repo a while ago, I'll try to find some time to fix it for senna.js as well.

**Comment by brunobasto** [comment]
@fernandosouza, any updates on this?

Thx

**Comment by fernandosouza** [comment]
Yes, I have. The problem is that mentioned by Maira. This pull (https://github.com/liferay/senna.js/pull/189/commits/93466310fdc940e04f12ecc2f04fc9fada7b28ef) has fixed it by using JWT Travis addon (https://docs.travis-ci.com/user/sauce-connect/)

This issue can be closed.

**Comment by brunobasto** [comment]
Thans, @fernandosouza!
