### ISSUE TITLE
Feature request: nested routers

### ISSUE THREAD

**Issue by yuchi** [liferay/senna.js#180]
(This is not a specific issue so I’m not using the provided template. Sorry)

### Problem

In Liferay DXP, and in general on applications with a pluggable UI infrastructure, when Senna is enabled it is not possible to have “inner” SPAs. Let me show a portlet-oriented example (replace “portlet” with “widget” if you have a hard time understanding the example).

Let’s say that within a website I place a page with a portlet whose UI is written in React and React Router. That portlet has its own friendly URLs in the standard form `/<PAGE_FRNDY_URL>/-/<NAMESPACE>/*`. Without Senna enabled I could trap for all pages matching that pattern and behave on those, opting out to manage the transition when it is not my duty to do so. Also to be honest this would be managed directly by the browser.

[![Precursor](https://precursorapp.com/document/Senna-States-17592205162033.svg?x)](https://precursorapp.com/document/Senna-States-17592205162033)

In this scheme the transition between states `1-2` and `3-4` would be managed by the browser.
Moving in the opposite direction that would happen too:
-  `4` to `3` would cause the page to reload,
- `3` to `2` would be sent through the History APIs,
- `2` to `1` would reload the page too.

### Solution

Senna would need to be able to have a “sub-API” to listen for changes in a similar manner.

So instead of doing this:

```js
window.addEventListener('popstate', event => { … });
// and
history.pushState( … );
```

I would do something along these lines:

```js
Liferay.SPA.app.onPopstate(event => { … });
// and
Liferay.SPA.app.window.pushState( … );
```

Senna should treat its own transitions as full page reloads, clearing `popstate` listeners.
To do so when an app uses Senna’s `pushState` it would be set as a sub state of the current main one. When we exit the main state Senna would know that it has to clear listeners.

[![Precursor](https://precursorapp.com/document/Senna-States-NG-17592205162252.svg?auth-token=)](https://precursorapp.com/document/Senna-States-NG-17592205162252)

**Comment by brunobasto** [comment]
Hey @yuchi,

I'm not sure I fully understand the issue. So, basically, you are experiencing issues when doing `history.pushState( … );` on your own? In theory, if the new url is not routed by Senna, Senna shouldn't be interfering with it. Is that what's happening?

**Comment by yuchi** [comment]
Actually I prevented myself to even try to implement a custom SPA on a page that has Senna on it.

As I saw from the code we are using a `senna` attribute on the state to manage if we need to trap it or not. The issue is that moving back to a page loaded with senna would still have `senna` set to `true`.

Let me create a minimal test case.

**Comment by yuchi** [comment]
@brunobasto I probably made a small enough test case. Have a look here: https://github.com/yuchi/senna-nester-routes-test-case

Make it start with

    npm install
    npm start

### Steps to reproduce

- launch the test case with `npm start`
- visit `http://localhost:3000/index.html`
- click `other.html`
- click `Push state`
- click `Push state` again
- go back with your browser history
- the text _«Status is 1 from history (app?)»_ is shown
- go back with your browser history again

### Expected result

- the text _«Status is 0 from history (app?)»_ should be shown

### Actual result

- the text _«Status is 0 from senna/browser»_ is shown instead

### Notes

I could actually solve this very easily by calling `window.history.replaceState` and removing the `senna` property from the state. ***But*** if I go one step before the first page with the history and then forward again, then the page should be loaded through Senna, without the `senna` attribute no one would actually manage the `popstate` event.

Please sorry if my explanation is unclear.

**Comment by brunobasto** [comment]
Hey @yuchi, thanks for providing the test case with detailed steps to reproduce. I'll take a look and let you know how it goes.

**Comment by eduardolundgren** [comment]
I cannot run the test case provided on the issue https://gist.github.com/eduardolundgren/1588bdb3439c6ba8ed4a220d97264811. Do you require any specific node version?

When senna detects `popstate` it checks for `state.senna` flag to be there, if it’s not there it should ignore completely or reload the page in case of back button is pressed, this might be what is causing issues for you.

If your issue is related to that:
 1) we could add an option to completely ignore states without `senna` flag
 2) we could add an option to not reload the page when back is pressed and `senna` flag is not present.

**Comment by yuchi** [comment]
Looks like `serve` requires Node v6+.
Just run `npm run build` and then open an HTTP server on the *public* directory.

**Comment by eduardolundgren** [comment]
When you go from: 
* index.html `(s1)` -> other.html `(s2)` -> other.html?count=1 `(s3)` -> other.html?count=2 `(s4)`

Then when you go back from:
 * other.html?count=2 `(s4)` ->  other.html?count=1 `(s3)`

Then when you go back again from:
* other.html?count=1 `(s3)` ->  other.html `(s2)` it should render `(s2)`

Considering that `(s1)` and `(s2)` are Senna states, it must navigate through Senna to guarantee the consistency. It’s accurate that senna handles this popstate. A popstate is not a transition between the current path and the future path, it’s a return to an old state.

The way you are trying to use is different from push/pop state concept.
I understand what you meant but it would require to be done manually or disabling Senna.
I am afraid there is no generic way to handle this situation.

**Comment by yuchi** [comment]
If you add a `s5` where the user goes back to index.html and then you use the history drop down to skip to `s3` nothing will happen because:
- senna should navigate but it will not (there's no `senna:true` attribute in the state)
- a pop state event is triggered but the correct listener is not fired since it correctly unloaded when moving from s4 to s5

**Comment by faragos** [comment]
What is the current state of this issue? I tried it but came to a problem with the history back. Did something change since 2016 or is it still not possible to use a Vue/React-Router inside a Senna.js application?

**Comment by yuchi** [comment]
AFAIK there has been no progress on this issue.

**Comment by wincent** [comment]
We're about to archive this repo and mark it as read-only. As [explained here](https://github.com/liferay/liferay-frontend-projects/blob/eb83cc6c28fc68e6e70aed8a22f1b2fdf31ac277/maintenance/projects/senna/README.md) the Senna code base has been ingested into Liferay DXP itself in the form of the `frontend-js-spa-web` module, and we have migrated the v2.x history over into [the liferay-frontend-projects monorepo](https://github.com/liferay/liferay-frontend-projects) so that we can keep our stuff together (and have uniform testing, linting, building etc) and will cut any necessary maintenance releases from there.

So as to clean out stale issues, I am closing anything that hasn't had any activity in the last year. If this is still relevant, would you mind [opening an issue over there](https://github.com/liferay/liferay-frontend-projects/issues/new?assignees=&labels=senna&template=senna.md) instead?
