### ISSUE TITLE
Possibility to avoid appending <div> child to a surface element.

### ISSUE THREAD

**Issue by bojanvidanovic** [liferay/senna.js#227]
### Expected behaviour

Once specified the surface element, SennaJS should not append a child div, and should operate directly and only on specified surface element without appending any child elements.

### Actual behaviour

Once specified the surface element, SennaJS will append a child div:

    <div id="main-default" class="flipped" style="display: block;">

The problem with this solution is that it will break an increasingly used CSS Grid property, and needs a 'hack' to work on an appended child element.

### Steps to reproduce

Any SennaJS app with dynamic content.

**Comment by brunobasto** [comment]
Hey @bojanvidanovic,

A agree that the way it is right now is not ideal, but I'll tag this one as an improvement since it has been like that since day one.

**Comment by wincent** [comment]
We're about to archive this repo and mark it as read-only. As [explained here](https://github.com/liferay/liferay-frontend-projects/blob/eb83cc6c28fc68e6e70aed8a22f1b2fdf31ac277/maintenance/projects/senna/README.md) the Senna code base has been ingested into Liferay DXP itself in the form of the `frontend-js-spa-web` module, and we have migrated the v2.x history over into [the liferay-frontend-projects monorepo](https://github.com/liferay/liferay-frontend-projects) so that we can keep our stuff together (and have uniform testing, linting, building etc) and will cut any necessary maintenance releases from there.

So as to clean out stale issues, I am closing anything that hasn't had any activity in the last year. If this is still relevant, would you mind [opening an issue over there](https://github.com/liferay/liferay-frontend-projects/issues/new?assignees=&labels=senna&template=senna.md) instead?
