### ISSUE TITLE
Anchor scroll after page loaded for the first time

### ISSUE THREAD

**Issue by caneta** [liferay/senna.js#229]
On a Liferay 7 DXP fixpack 31, I have the following problem:
on my website I have an header with position fixed of 200px and when I cut and paste an url like **http://mywebsite.com#myanchor** I get that the anchor is displayed at the top of the page but uder the header.
I would like to scroll it down 200px, in order to see properly the anchor, but I'm not able to catch an event in order to do that.
In other words, I'm able to do that after a `endNavigate` event with
```
Liferay.SPA.app.on('endNavigate', function () {
  window.scrollTo(0, 200)
}); // on endNavigate event
```
But it doesn't work if I load a page for the first time (`Liferay.on('SPAReady', function(){})` do not work either).
THis does not work if I put the url with cut and paste in browser address field or even if I click on the link **http://mywebsite.com#myanchor** from an external resource, for example an email.

How to perform a scroll in this case? Which event have I to use?

Thank you.

**Comment by caneta** [comment]
Probably I would like to have an event like already described on issue #140

**Comment by matuzalemsteles** [comment]
Hey @caneta,

Sorry for the delay, can you see if the `endNavigate` event is called? passing some `console.log` to check. Thanks!

**Comment by caneta** [comment]
No, the `endNavigate` event is not fired at page load, this is the problem depicted in #140 too.

**Comment by wincent** [comment]
We're about to archive this repo and mark it as read-only. As [explained here](https://github.com/liferay/liferay-frontend-projects/blob/eb83cc6c28fc68e6e70aed8a22f1b2fdf31ac277/maintenance/projects/senna/README.md) the Senna code base has been ingested into Liferay DXP itself in the form of the `frontend-js-spa-web` module, and we have migrated the v2.x history over into [the liferay-frontend-projects monorepo](https://github.com/liferay/liferay-frontend-projects) so that we can keep our stuff together (and have uniform testing, linting, building etc) and will cut any necessary maintenance releases from there.

So as to clean out stale issues, I am closing anything that hasn't had any activity in the last year. If this is still relevant, would you mind [opening an issue over there](https://github.com/liferay/liferay-frontend-projects/issues/new?assignees=&labels=senna&template=senna.md) instead?
