### ISSUE TITLE
Explicitly don't track elements with data-senna-track="false"

### ISSUE THREAD

**Issue by stiemannkj1** [liferay/senna.js#253]
Due to a certain use case in Liferay Portal, I was required to add `data-senna-track="false"` to an element to avoid tracking it. This currently works correctly, however, it feels like I'm relying on undefined behavior. Could it be made explicit in the code and/or the documentation that `false` is a valid value for `data-senna-track` and that resources with `data-senna-track="false"` will be ignored by SennaJS?

[`HtmlScreen.js` includes some selectors which will still capture `data-senna-track="false"` elements](https://github.com/liferay/senna.js/blob/e0487d8/src/screen/HtmlScreen.js#L331-L334) although they are only used [to compare with permanent elements and then discarded](https://github.com/liferay/senna.js/blob/e0487d8/src/screen/HtmlScreen.js#L164-L187). Perhaps a different selector should be used or a check should be made before using an element with `data-senna-track="false"`.

**Comment by stiemannkj1** [comment]
`'script[data-senna-track]:not([data-senna-track="false"]` might work as a selector, although I'm not sure if it's compatible with all browsers.

**Comment by wincent** [comment]
We're about to archive this repo and mark it as read-only. As [explained here](https://github.com/liferay/liferay-frontend-projects/blob/eb83cc6c28fc68e6e70aed8a22f1b2fdf31ac277/maintenance/projects/senna/README.md) the Senna code base has been ingested into Liferay DXP itself in the form of the `frontend-js-spa-web` module, and we have migrated the v2.x history over into [the liferay-frontend-projects monorepo](https://github.com/liferay/liferay-frontend-projects) so that we can keep our stuff together (and have uniform testing, linting, building etc) and will cut any necessary maintenance releases from there.

So as to clean out stale issues, I am closing anything that hasn't had any activity in the last year. If this is still relevant, would you mind [opening an issue over there](https://github.com/liferay/liferay-frontend-projects/issues/new?assignees=&labels=senna&template=senna.md) instead?
