### ISSUE TITLE
Cancel navigation duplicates surfaces

### ISSUE THREAD

**Issue by antonio-ortega** [liferay/senna.js#262]
### Expected behaviour

Surfaces are not duplicated if I cancelled navigation.

### Actual behaviour

Surfaces are duplicated when cancelling navigation leading to problems like duplicated id, etc.

### Steps to reproduce

1. Create an app with two pages (PageA and PageB) in a such a way that you navigate between them using senna.js
2. Being on PageA, click on link to navigate to PageB.
3. Quickly, before PageB is loaded, click again to navigate to PageA.
4. Inspect the DOM and you'll see surfaces duplicated.

### Browsers affected

It's easier to reproduce on IE11 because is slower, but you can use CPU throttling in Chrome.

**Comment by cleydyr** [comment]
Hey, guys. This fix is a dependency of a bug for Liferay Portal, so I'd like to give a heads up here, since a couple of weeks ago was the last commit referencing this issue. Is there any update?

Regards!

**Comment by jbalsas** [comment]
Hey @cleydyr, thanks for reaching out. We're aware of this. You can follow the progress on [this PR](https://github.com/liferay/senna.js/pull/266). 

We aren't sure if this change introduces a regression that might affect analytics. Since we think this component is more important than the mentioned bug (which is low priority), we don't want to risk it without being 100% sure. @brunobasto will take a look as soon as he can.

**Comment by cleydyr** [comment]
Thanks for providing the related PR so that I can subscribe to it. I understand the issue with the different priorities and how Analytics affects the resolution of the original bug affecting Liferay Portal.

Regards!
