### ISSUE TITLE
Style tags with permanent track will duplicate a lot

### ISSUE THREAD

**Issue by diegonvs** [liferay/senna.js#268]
### Expected behaviour

When i set a `<style>` tag into <head>, tracking it with `data-senna-track="permanent"` i don't want that stylesheet duplicates when i navigate into the same page.

### Steps to reproduce

1. Set trackable resources of a page with a `<link>` and a `<style>` tag with any Stylesheet that you think.
2. Navigate using SPA into the same page
3. When you inspect the page you will se a duplicated `<style>` tag into the `<head>` of the page.
4. Once you navigate this `<style>` tag will multiply.

### Browsers affected

Latest Chrome, Firefox, Safari and IE11

**Comment by diegonvs** [comment]
We need set a resourceKey(a `id`, `href` or a `src` attribute) for any permanent resources to not reproduce this.

**Comment by wincent** [comment]
We're about to archive this repo and mark it as read-only. As [explained here](https://github.com/liferay/liferay-frontend-projects/blob/eb83cc6c28fc68e6e70aed8a22f1b2fdf31ac277/maintenance/projects/senna/README.md) the Senna code base has been ingested into Liferay DXP itself in the form of the `frontend-js-spa-web` module, and we have migrated the v2.x history over into [the liferay-frontend-projects monorepo](https://github.com/liferay/liferay-frontend-projects) so that we can keep our stuff together (and have uniform testing, linting, building etc) and will cut any necessary maintenance releases from there.

So as to clean out stale issues, I am closing anything that hasn't had any activity in the last year. If this is still relevant, would you mind [opening an issue over there](https://github.com/liferay/liferay-frontend-projects/issues/new?assignees=&labels=senna&template=senna.md) instead?
