### ISSUE TITLE
Senna doesn't navigate correctly using a <a /> tag inside a <svg /> tag

### ISSUE THREAD

**Issue by interaminense** [liferay/senna.js#274]
### Expected behaviour

There is a `<a />` tag inside SVG and I hope that when I click the link, Senna can load the page in SPA.

### Actual behaviour

Clicking on the link displays a javascript error in the console:
<img width="490" alt="screen shot 2018-08-29 at 19 28 31" src="https://user-images.githubusercontent.com/12699849/44819110-fb6c0b80-abc1-11e8-943d-885fd34de074.png">

This happens because the type of the `<a />` tag inside an SVG is different from the `<a />` tag inside HTML and Senna expects a string instead of an `SVGAnimatedString` object:
<img width="1406" alt="screen shot 2018-08-29 at 19 27 20" src="https://user-images.githubusercontent.com/12699849/44819129-15a5e980-abc2-11e8-816e-1ac96757078e.png">

### Steps to reproduce

1. Add a `<a />` tag inside an SVG:
<img width="838" alt="screen shot 2018-08-29 at 19 33 27" src="https://user-images.githubusercontent.com/12699849/44819259-9664e580-abc2-11e8-91e2-ccb5caa422e1.png">
2. Click on the link to navigate with SPA;

### Browsers affected

Shouldn't be working on all browsers

**Comment by wincent** [comment]
We're about to archive this repo and mark it as read-only. As [explained here](https://github.com/liferay/liferay-frontend-projects/blob/eb83cc6c28fc68e6e70aed8a22f1b2fdf31ac277/maintenance/projects/senna/README.md) the Senna code base has been ingested into Liferay DXP itself in the form of the `frontend-js-spa-web` module, and we have migrated the v2.x history over into [the liferay-frontend-projects monorepo](https://github.com/liferay/liferay-frontend-projects) so that we can keep our stuff together (and have uniform testing, linting, building etc) and will cut any necessary maintenance releases from there.

So as to clean out stale issues, I am closing anything that hasn't had any activity in the last year. If this is still relevant, would you mind [opening an issue over there](https://github.com/liferay/liferay-frontend-projects/issues/new?assignees=&labels=senna&template=senna.md) instead?
