### ISSUE TITLE
endNavigate when instantiated via data attributes

### ISSUE THREAD

**Issue by WHI-CH** [liferay/senna.js#288]
When Senna is instantiated via the data attributes, how does one access the Senna object normally available when it is created with "var app = new senna.App()"?
This info would be a good addition to the docs ;)

**Comment by ereinach** [comment]
up

**Comment by brunobasto** [comment]
If you have ES6 or AMD setup, one way would be to import https://github.com/liferay/senna.js/blob/master/src/app/dataAttributeHandler.js and call the `getApp()` method. If you are just using the global build, I think there's currently no way to do that. That's an improvement that could be made. @diegonvs what do you think?

**Comment by wincent** [comment]
We're about to archive this repo and mark it as read-only. As [explained here](https://github.com/liferay/liferay-frontend-projects/blob/eb83cc6c28fc68e6e70aed8a22f1b2fdf31ac277/maintenance/projects/senna/README.md) the Senna code base has been ingested into Liferay DXP itself in the form of the `frontend-js-spa-web` module, and we have migrated the v2.x history over into [the liferay-frontend-projects monorepo](https://github.com/liferay/liferay-frontend-projects) so that we can keep our stuff together (and have uniform testing, linting, building etc) and will cut any necessary maintenance releases from there.

So as to clean out stale issues, I am closing anything that hasn't had any activity in the last year. If this is still relevant, would you mind [opening an issue over there](https://github.com/liferay/liferay-frontend-projects/issues/new?assignees=&labels=senna&template=senna.md) instead?
