### ISSUE TITLE
Browser support matrix doesn't mention support for any browser other than Edge in Windows 10

### ISSUE THREAD

**Issue by duracell80** [liferay/senna.js#294]
![outofdate](https://user-images.githubusercontent.com/18121278/49093550-f4d54a80-f229-11e8-9cc7-c86e611f4fab.JPG)

**Comment by jbalsas** [comment]
hey @duracell80, isn't `Edge` running on `Win10`? Are you looking to get other browsers there as well? If so, which ones?

**Comment by duracell80** [comment]
Enterprises most likely won't be using Edge in Windows 10 because many web apps aren't compatible, Edge in general has an adoption issue that Microsoft have acknowledged. So enterprise will be using IE11 on Win10. 

The issue I see is there is no support for Windows 10 browsers period?

Even worse, by this chart, Chrome which is evergreen is not supported at 70 on Windows 7?

**Comment by jbalsas** [comment]
Hey @duracell80, please don't read things into it or make assumptions. 

Windows 10 browsers are supported. Just the test matrix we run on Saucelabs is not going through them. Browsers and OSs keep changing and updating. We'll update the test matrix accordingly.

Chrome 70 on Windows7 failure is likely a fluke, but we'll investigate. Again, that doesn't mean it's not supported.

/cc @matuzalemsteles?

**Comment by jbalsas** [comment]
Seeing the header on top of the browser test result, I guess that's where the confusion is coming from. @matuzalemsteles, @brunobasto, maybe we can find a better way to present that? What are others doing?

**Comment by duracell80** [comment]
Just taking it as factual at face value, Windows 7 users are straight out of luck unless using Firefox and Windows 10 isn't even in the picture.

**Comment by duracell80** [comment]
Just raising the concern that automated testing in Windows 10 is almost non-existent?

**Comment by jbalsas** [comment]
Yeah, we'll update the automated test matrix. Do you think we need to keep Windows7, or we can simply move into Windows10?

**Comment by matuzalemsteles** [comment]
I would not make so much assumption based on the operating system, the important here are the versions of browsers, they should operate the same on any operating system once they follow a specification. So from this image we just want to demonstrate that we are supporting the versions of each browser.

Chrome failing in Win 7 because it is an old test it is not running the latest changes...

hey @jbalsas others do not usually put information about browser compatibility, this is not explicit, just looking at the tests, but the vast majority do not test on all operating systems...

**Comment by duracell80** [comment]
Deprecated in what sense? The vendor has end of life on this browser at 2025 fro Enterprise (all while the browser fails to keep up with technology). IE11 will behave slightly different between Windows 7, 8.1 and 10. But really the issue is that there's a lack of Windows 10 in these tests for browsers other than Edge.

Edge is failing to get adopted also.

**Comment by matuzalemsteles** [comment]
Deprecated was a bit strong, sorry for that, but what I meant is not to receive more evolutions, such as support [ES6](http://kangax.github.io/compat-table/es6/)... for example. [Only being maintained for security issues and compatibility fix](https://www.microsoft.com/en-us/WindowsForBusiness/End-of-IE-support).

I know Edge is not having as much adoption as it should have ... more was chosen by Microsoft, they are evolving and supporting the latest specs that is most important to us here... Please do not misunderstand, I am not disagreeing with you.

Tests in Windows 10, we must put other browsers, let's work on it in the next days.

**Comment by wincent** [comment]
We're about to archive this repo and mark it as read-only. As [explained here](https://github.com/liferay/liferay-frontend-projects/blob/eb83cc6c28fc68e6e70aed8a22f1b2fdf31ac277/maintenance/projects/senna/README.md) the Senna code base has been ingested into Liferay DXP itself in the form of the `frontend-js-spa-web` module, and we have migrated the v2.x history over into [the liferay-frontend-projects monorepo](https://github.com/liferay/liferay-frontend-projects) so that we can keep our stuff together (and have uniform testing, linting, building etc) and will cut any necessary maintenance releases from there.

So as to clean out stale issues, I am closing anything that hasn't had any activity in the last year. If this is still relevant, would you mind [opening an issue over there](https://github.com/liferay/liferay-frontend-projects/issues/new?assignees=&labels=senna&template=senna.md) instead?
