### ISSUE TITLE
Senna moves focus away from autoFocus fields on refresh

### ISSUE THREAD

**Issue by fortunatomaldonado** [liferay/senna.js#314]
### Expected behaviour

By having a field with `autoFocus="true"`, the focus should be on the field after refreshing the page.

### Actual behaviour

The focus is seen on the field and then moved to the `body` of the page when the page is refreshed.

### Steps to reproduce

1. Deploy the jar
2. Add the login portlet to the front page.
3. Refresh the page.

### Browsers affected

I tested on all major browsers and they all produce this issue.

I was able to find the location where the focus is changed. After it appends `<div class="pt-0" id="wrapper"></div>` the focus is then changed to the `body`
https://github.com/liferay/senna.js/blob/master/src/surface/Surface.js#L173

[login-1.0.0.zip](https://github.com/liferay/senna.js/files/3483640/login-1.0.0.zip)

**Comment by diegonvs** [comment]
Hey @fortunatomaldonado,

This behavior is caused because the elements with `autoFocus` attribute are focused on `DOMContentLoaded` event. However, when navigating by SPA this event isn't being triggered. I made a fix here: https://github.com/liferay/senna.js/pull/315

**Comment by fortunatomaldonado** [comment]
Hello @diegonvs,

Thank you so much for your help on this!

**Comment by wincent** [comment]
We're about to archive this repo and mark it as read-only. As [explained here](https://github.com/liferay/liferay-frontend-projects/blob/eb83cc6c28fc68e6e70aed8a22f1b2fdf31ac277/maintenance/projects/senna/README.md) the Senna code base has been ingested into Liferay DXP itself in the form of the `frontend-js-spa-web` module, and we have migrated the v2.x history over into [the liferay-frontend-projects monorepo](https://github.com/liferay/liferay-frontend-projects) so that we can keep our stuff together (and have uniform testing, linting, building etc) and will cut any necessary maintenance releases from there.

So as to clean out stale issues, I am closing anything that hasn't had any activity in the last year. If this is still relevant, would you mind [opening an issue over there](https://github.com/liferay/liferay-frontend-projects/issues/new?assignees=&labels=senna&template=senna.md) instead?
