### ISSUE TITLE
Start navigation on mousedown instead of on click 

### ISSUE THREAD

**Issue by lneves12** [liferay/senna.js#321]
This was just an idea I had while looking at https://instant.page

What about triggering the senna navigaton on mouse down instead of mouse click? With that, we could have faster transitions on pages that are not cacheable by ~100ms.

I am willing to implement it directly on senna, but it would be nice to have your approval so I don't waste my time here :+1:

**Comment by lneves12** [comment]
First experiments: https://github.com/liferay/senna.js/pull/322

ping @diegonvs

**Comment by wincent** [comment]
We're about to archive this repo and mark it as read-only. As [explained here](https://github.com/liferay/liferay-frontend-projects/blob/eb83cc6c28fc68e6e70aed8a22f1b2fdf31ac277/maintenance/projects/senna/README.md) the Senna code base has been ingested into Liferay DXP itself in the form of the `frontend-js-spa-web` module, and we have migrated the v2.x history over into [the liferay-frontend-projects monorepo](https://github.com/liferay/liferay-frontend-projects) so that we can keep our stuff together (and have uniform testing, linting, building etc) and will cut any necessary maintenance releases from there.

So as to clean out stale issues, I am closing anything that hasn't had any activity in the last year. If this is still relevant, would you mind [opening an issue over there](https://github.com/liferay/liferay-frontend-projects/issues/new?assignees=&labels=senna&template=senna.md) instead?
