### ISSUE TITLE
Back button reloads the inital page

### ISSUE THREAD

**Issue by bojanvidanovic** [liferay/senna.js#330]
When a webpage is loaded, I can navigate seamlessly through all my links. The problem presents when I start using the back button to get back to the initial page which reloads the website.

### Steps to reproduce

This is present in one of your examples: [Email example](https://sennajs.com/examples/email/). If you click on one of the emails and then use the back button, it will reload the website.

I'm not sure if this is an issue or I am missing on something in the documentation.

**Comment by wincent** [comment]
We're about to archive this repo and mark it as read-only. As [explained here](https://github.com/liferay/liferay-frontend-projects/blob/eb83cc6c28fc68e6e70aed8a22f1b2fdf31ac277/maintenance/projects/senna/README.md) the Senna code base has been ingested into Liferay DXP itself in the form of the `frontend-js-spa-web` module, and we have migrated the v2.x history over into [the liferay-frontend-projects monorepo](https://github.com/liferay/liferay-frontend-projects) so that we can keep our stuff together (and have uniform testing, linting, building etc) and will cut any necessary maintenance releases from there.

So as to clean out stale issues, I am closing anything that hasn't had any activity in the last year. If this is still relevant, would you mind [opening an issue over there](https://github.com/liferay/liferay-frontend-projects/issues/new?assignees=&labels=senna&template=senna.md) instead?
