### ISSUE TITLE
How to flip a specific surface only?

### ISSUE THREAD

**Issue by bojanvidanovic** [liferay/senna.js#331]
**Task**: Change a specific surface for all routes with a regex.

I have two surfaces: main and list:
```
const app = new senna.App()
app.addSurfaces(['main', 'list'])
```
where the list is inside main, so they are nested.

Then I created a new Screen where I can manipulate only list surface and this is where the problems begin:

```
new senna.Route(/\/products\/categories\/(?/:.+)/g), () => {
  const screen = new senna.HtmlScreen()
  screen.setCacheable(true)
  screen.flip = surfaces => {
    // RETURN LIST SURFACE
  }
})
```
How can I define a custom screen and render only the surface I want? I just can understand it from the docs.

Thanks for this lovely lib.

**Comment by wincent** [comment]
We're about to archive this repo and mark it as read-only. As [explained here](https://github.com/liferay/liferay-frontend-projects/blob/eb83cc6c28fc68e6e70aed8a22f1b2fdf31ac277/maintenance/projects/senna/README.md) the Senna code base has been ingested into Liferay DXP itself in the form of the `frontend-js-spa-web` module, and we have migrated the v2.x history over into [the liferay-frontend-projects monorepo](https://github.com/liferay/liferay-frontend-projects) so that we can keep our stuff together (and have uniform testing, linting, building etc) and will cut any necessary maintenance releases from there.

So as to clean out stale issues, I am closing anything that hasn't had any activity in the last year. If this is still relevant, would you mind [opening an issue over there](https://github.com/liferay/liferay-frontend-projects/issues/new?assignees=&labels=senna&template=senna.md) instead?
