### ISSUE TITLE
Dynamically added classes to the head element gets removed on page change

### ISSUE THREAD

**Issue by bojanvidanovic** [liferay/senna.js#335]
### Expected behavior

Classes added via JS to the head element should not be removed on page change.

### Actual behaviour

On page change, Senna will append 'senna-loading' class to the head element, and on the end of transition will remove it toghether with all other dynamically added classes.

### Browsers affected

All.

**Comment by wincent** [comment]
We're about to archive this repo and mark it as read-only. As [explained here](https://github.com/liferay/liferay-frontend-projects/blob/eb83cc6c28fc68e6e70aed8a22f1b2fdf31ac277/maintenance/projects/senna/README.md) the Senna code base has been ingested into Liferay DXP itself in the form of the `frontend-js-spa-web` module, and we have migrated the v2.x history over into [the liferay-frontend-projects monorepo](https://github.com/liferay/liferay-frontend-projects) so that we can keep our stuff together (and have uniform testing, linting, building etc) and will cut any necessary maintenance releases from there.

So as to clean out stale issues, I am closing anything that hasn't had any activity in the last year. If this is still relevant, would you mind [opening an issue over there](https://github.com/liferay/liferay-frontend-projects/issues/new?assignees=&labels=senna&template=senna.md) instead?
