### ISSUE TITLE
Mio de mi

### ISSUE THREAD

**Issue by angelukas** [liferay/senna.js#347]
`###` Expected behaviour

I thought that by going to the page '...' and pressing the button '...' then '...' would happen.

### Actual behaviour

Instead of '...', what I saw was that '...' happened instead.

### Steps to reproduce

1. Go this JSFiddle, JSBin, CodePen, etc
4. Refresh the page and wait 5 secs
5. Finally the error will magically happen (if it is raining)

### Browsers affected

I tested on all major browsers and only IE 11 does not work.

**Comment by wincent** [comment]
We're about to archive this repo and mark it as read-only. As [explained here](https://github.com/liferay/liferay-frontend-projects/blob/eb83cc6c28fc68e6e70aed8a22f1b2fdf31ac277/maintenance/projects/senna/README.md) the Senna code base has been ingested into Liferay DXP itself in the form of the `frontend-js-spa-web` module, and we have migrated the v2.x history over into [the liferay-frontend-projects monorepo](https://github.com/liferay/liferay-frontend-projects) so that we can keep our stuff together (and have uniform testing, linting, building etc) and will cut any necessary maintenance releases from there.

So as to clean out stale issues, I am closing anything that doesn't seem immediately actionable. If this is still relevant, would you mind [opening an issue over there](https://github.com/liferay/liferay-frontend-projects/issues/new?assignees=&labels=senna&template=senna.md) instead?
