### ISSUE TITLE
Saving app.screens into localStorage

### ISSUE THREAD

**Issue by PH4NTOMiki** [liferay/senna.js#349]
@eduardolundgren @brunobasto It would be great if the screens could be cached in localStorage, when I call `JSON.stringify` on `app.screens` (Senna instance) and refresh the page and do `app.screens = JSON.parse(localStorage.sennaScreens)` it just doesn't work at all, it would be great if you could tell me how to do something similar to that, thank you for creating this amazing peace of software, I just wish that the feature like this would exist. Thanks

**Comment by wincent** [comment]
We're about to archive this repo and mark it as read-only. As [explained here](https://github.com/liferay/liferay-frontend-projects/blob/eb83cc6c28fc68e6e70aed8a22f1b2fdf31ac277/maintenance/projects/senna/README.md) the Senna code base has been ingested into Liferay DXP itself in the form of the `frontend-js-spa-web` module, and we have migrated the v2.x history over into [the liferay-frontend-projects monorepo](https://github.com/liferay/liferay-frontend-projects) so that we can keep our stuff together (and have uniform testing, linting, building etc) and will cut any necessary maintenance releases from there.

So as to clean out stale issues, I am closing this one because the mentioned folks no longer work at Liferay. If this is still relevant, would you mind [opening an issue over there](https://github.com/liferay/liferay-frontend-projects/issues/new?assignees=&labels=senna&template=senna.md) instead?
