### ISSUE TITLE
Integrate appveyor for Windows based CI or find a way to test in Safari

### ISSUE THREAD

**Issue by FagnerMartinsBrack** [liferay/senna.js#94]
I cloned this project again to start working on #60, but I realized there are some problems running the tests with Safari: #91, #92, #93.

I can't say if this is only happening on Windows because Travis-CI doesn't seem to test on Safari: https://github.com/eduardolundgren/senna/blob/234dff5fd48ad75fc6a0eca8748dc907540a07e1/karma.conf.js#L40-L47

It would be nice to find a way to test the project in all supported browsers through CI to prevent this kind of problem. I don't know if one can run Safari with appveyor, need to take a look.

By the way, is it safe to assume Safari is working in other environments and this problem is just on Windows?

**Comment by henvic** [comment]
We could also use either:
a) a Selenium cloud service like SauceLabs or BrowserStack
b) a OS X vm on Travis.

I've tried both approaches and had problems with them.

Both Selenium / WebDriver cloud services failed to deliver the expected availability or took much longer than the allowed time a process has to build on Travis.

Travis OS X environment is still experimental and they're not allowing new testers so far.

I remember trying AppVeyor for testing with IE but don't recall if it was on this project or another one. Anyways, I remember I found it was not straight-forward and I dropped my tests due to higher priorities I had back then. Perhaps you can provide us a pull request adding this for common supported IE 10+ using that as well.

**Comment by FagnerMartinsBrack** [comment]
Last time I checked, Browserstack didn't provided free open source service (not trial) in the home page, but it seems you can [ask for it](http://qr.ae/QVPQz).

> Perhaps you can provide us a pull request adding this for common supported IE 10+ using that as well.

If that is possible, I may try to do that in a fork and send a pull request explaining the processes used to achieve the result.

**Comment by FagnerMartinsBrack** [comment]
@henvic, @eduardolundgren 

I took a fast look into it and I will document here what I found:

* Sauce labs contains an [open source plan](http://saucelabs/opensauce) that allows unlimited time for open source projects.

* There is an online example of a setup using gulp, karma and saucelabs: https://github.com/pythonandchips/glasgowjs-karma-saucelabs-gulp

* It seems you can easily integrate Travis CI to run sauce labs in commits, but [there are issues with authentication](https://github.com/carhartl/jquery-cookie/issues/268#issue-28485738) when running with pull requests. In this case there is this project actively maintaned and used by Twitter Bootstrap that runs a bot on pull requests: [Savage](https://github.com/cvrebert/savage)

I might be going too far and maybe running cross-browser tests on pull requests is not that critical right now, but exposing errors in Windows Safari for the maintainers of senna is very important.

X-ref: https://github.com/eduardolundgren/senna/issues/52

**Comment by henvic** [comment]
Yeah. Running cross-browser tests on pull requests would be pretty nice so that whoever is making a change would have immediately feedback, however it's not critical at all and we wouldn't like maintaining infra-structures to do things like that currently unless critical.

**Comment by eduardolundgren** [comment]
Now it's integrated with SauceLabs on v1.0.0-alpha. Thanks.
